name: Deploy to Firebase Hosting (Development)
'on':
  push:
    branches:
      - dev
      - develop
jobs:
  build_and_deploy_dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GEOHOG }}'
          channelId: develop
          projectId: geohog
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels